modLoader = "javafml"
loaderVersion = "[1,)"
license="MIT"

issueTrackerURL="https://github.com/OffsetMods538/Loot-Table-Modifier/issues"


[[mixins]]
config="loot-table-modifier.modded.mixins.json"
[[mixins]]
config="loot-table-modifier.version.modded.mixins.json"


[[mods]]
modId="loot_table_modifier"
version="${modVersion}"
displayName="Loot Table Modifier"
description="Makes it possible to modify instead of replace loot tables through datapacks"
logoFile="assets/loot-table-modifier/icon.png"
logoBlur=false
features={javaVersion="[21,)"}
modUrl="https://modrinth.com/mod/loot-table-modifier"
authors="OffsetMonkey538"
displayURL="https://modrinth.com/mod/loot-table-modifier"


[[dependencies.loot_table_modifier]]
modId="minecraft"
type="required"
versionRange="${neoforgeSupportedMinecraftVersions}"
ordering="NONE"
side="BOTH"
